### PR TITLE
2019-06-11-speed-limits: typo

### PR DESCRIPTION
**Pull request by TApplencourt**
First thanks you a lot for this blog post!

This small, and arguiably not important PR, fix 2 typos:

1.
> Like loads, a store that crosses a cache line counts as two, but other unaligned stores only count as on Intel.

-> Missing  one *one* I guess

2.
> My varying the number of filler instructions and checking whether the loads executed in parallel or serially

My -> By

Thanks again,

### CODE REVIEW

**Comment by travisdowns** [comment]
Thanks @TApplencourt - fixes merged and credited you at the end.

Kind of cool using github pull requests to update a blog :).

**Comment by TApplencourt** [comment]
> Kind of cool using github pull requests to update a blog :).
Agree! It's quite convenient.  Maybe the next step is to open issues to replace comments. :p

**Comment by travisdowns** [comment]
@TApplencourt  - heh, I think you were joking, but apparently one of the flows for comments on static sites hosted by github is more or less exactly that: so javascript that turns every comment turns into a pull request and then you moderate it by accepting the request.

Not sure if that's a good UI, but I'm still looking for a comment system. Having them ultimately stored here in this repository seems like the idea, although it would mean that all information is public, but as long as you make that clear I guess it's OK?

**Comment by TApplencourt** [comment]
I was half joking.  But thinking a little more, It makes sense to abuse Git and GitHub to do so.

> but as long as you make that clear I guess it's OK?
For sure. And add worst, you can remove all personal information after accepting the PR (by changing      GIT_COMMITTER_{NAME,EMAIL}  of the particular commit, for example).

**Pull request merged**
