### PR TITLE
Add GitHub Issue Button

### PR DESCRIPTION
**Pull request by techboyg5**
This adds a "GitHub" dropdown button next to the title of each post, with various options. Ready to be merged!

[Demo](https://projects.techboyg5blog.com/travisdowns.github.io/blog/2020/08/19/icl-avx512-freq.html)

### CODE REVIEW

**Comment by techboyg5** [comment]
OOps! Don't meage! I need a fix!

**Comment by travisdowns** [comment]
@techboyg5 - I am sorry I haven't been able to look at this. I haven't had any time for this stuff lately. That said, I appreciate your contributions here and I do plan to look at them. Can I keep this PR open as a reminder to look at it?

At some point in 2020 I hope to have time to look. Again, I am thankful your suggestions and work here and don't want you to take my silence so far as lack of appreciation: it is only a lack of time on my part.

**Comment by techboyg5** [comment]
> @techboyg5 - I am sorry I haven't been able to look at this. I haven't had any time for this stuff lately. That said, I appreciate your contributions here and I do plan to look at them. Can I keep this PR open as a reminder to look at it?
> 
> At some point in 2020 I hope to have time to look. Again, I am thankful your suggestions and work here and don't want you to take my silence so far as lack of appreciation: it is only a lack of time on my part.

Great idea!
I just saw this in my GitHub "Recent Activity".

**Comment by techboyg5** [comment]
Can we merge this now?

**Comment by travisdowns** [comment]
@techboyg5 - I am looking into what this does locally.

**Comment by travisdowns** [comment]
@techboyg5 - I don't want to be a jerk, but I don't think I'm inclined to pull this.

At a high level I think the idea of allowing easy access to submit PRs on a post (in particular, out of the three things this offers) is probably a good idea. I'm a bit concerned the current solution is overkill: including a whole new CSS file (from a 3rd party server), including the javascript (from your heroku server), etc. 

Of course, I could copy all these resources locally so they are served out of the same repo. Still, I would have other concerns: the dropdown "pops in" in two or three stages in my testing (first not present, then present as text, then as a dropdown) which is distracting. It kind of impinges on the bounding box for the title, causing the title to wrap oddly sometimes, e.g. like so:

title example

I try to keep the blog _fairly_ minimal, as I'm very from an expert in html, css, etc, so if I did want to add a link to create a PR, I think a plain snippet of html would do fine.

I do appreciate the effort and collaboration from your side, and I apologize for the fact that my relatively conservative stance here means it's hard for me to merge this type of thing.

**Comment by techboyg5** [comment]
Thank you for your suggestions! I will close this now.

**Comment by travisdowns** [comment]
> Thank you for your suggestions! I will close this now.

Thank you for your passion to make this blog better!

**Pull request closed without merging**
